- name: Install public key for passwordless access
  authorized_key:
    user: vogels
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/id_vogels_epfl.pub
    - public_keys/id_rsa.pub
- name: Deploy my private key
  copy:
    src: ~/.ssh/id_vogels_epfl
    dest: ~/.ssh/id_vogels_epfl
    mode: 0600
- name: Deploy my public key
  copy:
    src: ~/.ssh/id_vogels_epfl.pub
    dest: ~/.ssh/id_vogels_epfl.pub
    mode: 0600
- name: .gitconfig
  copy:
    src: gitconfig
    dest: ~/.gitconfig
- name: .profile
  copy:
    src: profile
    dest: ~/.profile
- name: Cloning  oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
- name: ZSH Config
  template:
    src: zshrc.j2
    dest: ~/.zshrc
# Mounting /mlo-container-scratch leads to not being able to login after reboot
# - name: Mount /mlo-container-scratch
#   block:
#     - file: path=/mlo-container-scratch state=directory
#     - copy:
#         src: "files/mlo.ceph.container.client.key"
#         dest: "/etc/ceph/mlo.ceph.container.client.key"
#     - mount:
#         path: /mlo-container-scratch
#         src: icadmin006,icadmin007,icadmin008:/mlo-scratch
#         fstype: ceph
#         opts: rw,relatime,name=mlo,secretfile=/etc/ceph/mlo.ceph.container.client.key,acl,noatime,nodiratime
#         state: mounted
- name: Packages that are not in Anaconda by default
  pip:
    name: "{{ item }}"
    state: latest
    executable: /opt/anaconda3/bin/pip
    extra_args: --user
  loop:
    - GitPython
    - influxdb
    - pymongo
    - pytelegraf
    - pyarrow

# JobMonitor
- name: Clone jobmonitor repo
  git:
    repo: git@github.com:epfml/job-monitor.git
    version: master
    dest: ~/install/job-monitor
    accept_hostkey: yes
  tags: 
    - jobmonitor
- name: Install jobmonitor
  command: python setup.py develop
  args:
    chdir: ~/install/job-monitor
  tags: 
  - jobmonitor

# Kubectl settings
- name: Deploy my Kubectl settings
  copy:
    src: ~/.kube/{{item}}
    dest: ~/.kube/{{item}}
    mode: 0600
  loop:
  - config
  - vogels.crt
  - vogels.key
  tags:
  - kubectl
